version: "3.9"
services:
  mongodb:
    image: mongo:latest
    expose:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=scholarsome"
      - "MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}"
      - "MONGO_INITDB_DATABASE=scholarsome"
    volumes:
      - mongodb:/data/db
    restart: always
  scholarsome:
    build:
      context: .
      dockerfile: Dockerfile
    platform: "linux/amd64"
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
#      - "(your ssl port):8443"
    environment:
      - "NODE_ENV=${NODE_ENV}"
      - "DATABASE_URL=mongodb://scholarsome:${DATABASE_PASSWORD}@mongodb:27017/scholarsome?authSource=admin"
      - "JWT_SECRET=${JWT_SECRET}"
      - "HTTP_PORT=${HTTP_PORT}"
      - "STORAGE_TYPE=${STORAGE_TYPE}"
      - "STORAGE_LOCAL_DIR=/data"
      - "S3_STORAGE_ENDPOINT=${S3_STORAGE_ENDPOINT}"
      - "S3_STORAGE_ACCESS_KEY=${S3_STORAGE_ACCESS_KEY}"
      - "S3_STORAGE_SECRET_KEY=${S3_STORAGE_SECRET_KEY}"
      - "S3_STORAGE_REGION=${S3_STORAGE_REGION}"
      - "S3_STORAGE_BUCKET=${S3_STORAGE_BUCKET}"
      - "SMTP_HOST=${SMTP_HOST}"
      - "SMTP_PORT=${SMTP_PORT}"
      - "SMTP_USERNAME=${SMTP_USERNAME}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
      - "HOST=${HOST}"
      - "SSL_KEY_BASE64=${SSL_KEY_BASE64}"
      - "SSL_CERT_BASE64=${SSL_CERT_BASE64}"
      - "SCHOLARSOME_RECAPTCHA_SITE=${RECAPTCHA_SITE}"
      - "SCHOLARSOME_RECAPTCHA_SECRET=${RECAPTCHA_SECRET}"
      - "GROQ_API_KEY=${GROQ_API_KEY}"
    volumes:
      - scholarsome:/data
    depends_on:
      - mongodb
    restart: always
volumes:
  mongodb:
  scholarsome:
